home:
  path: /
  controller: App\Controller\HomeController::index

proper-home:
  path: /home
  controller: App\Controller\HomeController::properIndex

products:
  path: /products
  controller: App\Controller\HomeController::products